export default {
  exportMarkdownFile: 'export-markdown-file',
  exportPng: 'export-png',
  exportFile: 'export-file',
  exportMarkdownFiles: 'export-markdown-files',
  importImage: 'import-image',
  uploadImages: 'upload-images',
  checkUpdate: 'check-update',
  needUpdate: 'need-update',
  quitAndUpdate: 'quit-and-install',
  remoteRequest: 'remote-request',
  getCacheImage: 'get-cache-image',
  saveTempImage: 'save-temp-image',
  loadTheme: 'load-theme',
  openThemeFolder: 'open-theme-folder',
  openLogFiles: 'open-log-files',
  refreshThemeFolder: 'refresh-theme-folder',
  getLocalFileData: 'get-local-file-data',
  saveUploadedImage: 'save-uploaded-image'
}
